[[chapter2]]
== Instructions

<<<
[#insns-ldatomic,reftext="Load Atomic Ordered"]
=== Load Atomic Ordered

Synopsis::
Loads size bytes of memory from the address in _rs1_ atomically and subject to the ordering requirements.

Mnemonic::
====
lb.{aq,aq.rl} _rd_, (_rs1_)

lh.{aq,aq.rl} _rd_, (_rs1_)

lw.{aq,aq.rl} _rd_, (_rs1_)

ld.{aq,aq.rl} _rd_, (_rs1_)

lq.{aq,aq.rl} _rd_, (_rs1_)
====
Encoding::
[wavedrom, ,svg]
....
{reg: [
  {bits: 7,  name: 'opcode',    attr: ['7', 'AMO'], type: 8},
  {bits: 5,  name: 'rd',        attr: ['5', 'dest'], type: 2},
  {bits: 3,  name: 'funct3',    attr: ['3', 'width'], type: 8},
  {bits: 5,  name: 'rs1',       attr: ['5', 'addr'], type: 4},
  {bits: 5,  name: 'rs2',       attr: ['5', '0'], type: 4},
  {bits: 1,  name: 'rl',        attr: ['1', 'ring'], type: 8},
  {bits: 1,  name: 'aq',        attr: ['1', 'orde'], type: 8},
  {bits: 5,  name: 'funct5',    attr: ['5', 'Load Ordered'], type: 8},
]}
....

Description::

This instruction loads size bytes of memory from rs1 atomically.
If the size is less than XLEN, it is sign-extended to fill the destination register.
This load may have ordering annotations _aq_ and _rl_ encoded in the instruction: if the bit _aq_ is set, the instruction has an "acquire-RCsc" annotation, and if the bit _rl_ is set, the instruction has a "release-RCsc" annotation.
If the implementation is not able to complete this load atomically it should generate an address-misaligned or access-fault exception.
The versions without the _aq_ bit set are RESERVED.
RV32 should not implement the d and q variant and RV64 should not implement the q variant.

funct5 for this instruction is 00110.

[NOTE]
====
Load-release is not seen as useful at this time, due to its lack of support in language-level memory models.
Load-atomic is similarly not seen as useful enough.
Instead, users should suitably align their pointers so that ordinary load instructions suffice.
====

SAIL code::
[source,sail]
--
TODO. steal code from https://github.com/riscv/sail-riscv/blob/master/model/riscv_insts_aext.sail
--

// load-ordered funct5 = 00110

<<<
[#insns-sdatomic,reftext="Store Atomic Ordered"]
=== Store Atomic Ordered

Synopsis::
Store size bytes of memory from _rs2_ to the address in _rs1_ atomically and subject to the ordering requirements.

Mnemonic::
====
sb.{rl,aq.rl} _rd_, _rs2_, (_rs1_)

sh.{rl,aq.rl} _rd_, _rs2_, (_rs1_)

sw.{rl,aq.rl} _rd_, _rs2_, (_rs1_)

sd.{rl,aq.rl} _rd_, _rs2_, (_rs1_)

sq.{rl,aq.rl} _rd_, _rs2_, (_rs1_)
====

Encoding::
[wavedrom, ,svg]
....
{reg: [
  {bits: 7,  name: 'opcode',    attr: ['7', 'AMO'], type: 8},
  {bits: 5,  name: 'rd',        attr: ['5', 'dest'], type: 2},
  {bits: 3,  name: 'funct3',    attr: ['3', 'width'], type: 8},
  {bits: 5,  name: 'rs1',       attr: ['5', 'addr'], type: 4},
  {bits: 5,  name: 'rs2',       attr: ['5', 'src'], type: 4},
  {bits: 1,  name: 'rl',        attr: ['1', 'ring'], type: 8},
  {bits: 1,  name: 'aq',        attr: ['1', 'orde'], type: 8},
  {bits: 5,  name: 'funct5',    attr: ['5', 'Store Ordered'], type: 8},
]}
....

Description::

This instruction stores size bytes of memory from rs1 atomically.
This store may have ordering annotations _aq_ and _rl_ encoded in the instruction: if the bit _aq_ is set, the instruction has an "acquire-RCsc" annotation, and if the bit _rl_ is set, the instruction has a "release-RCsc" annotation.
If the implementation is not able to complete this store atomically it should generate an address-misaligned or access-fault exception.
The versions without the _rl_ bit set are RESERVED.
RV32 should not implement the d and q variant and RV64 should not implement the q variant.

funct5 for this instruction is 00111.


[NOTE]
====
Store-acquire is not seen as useful at this time, due to its lack of support in language-level memory models.
Store-atomic is similarly not seen as useful enough.
Instead, users should suitably align their pointers so that ordinary store instructions suffice.
====

SAIL code::
[source,sail]
--
TODO. steal code from https://github.com/riscv/sail-riscv/blob/master/model/riscv_insts_aext.sail
--


// store-ordered funct5 = 00111