[[intro]]
== Introduction

The purpose of this extension is to provide load-acquire and store-release instructions into RISC-V.
As seen in cite:[hansdoc], these can be important for high performance designs.

They are also widely used in language-level memory models.
Both the Java cite:[manson2005java] and {cpp} cite:[boehm2008foundations] memory models make use of acquire-release semantics, and {cpp}'s `atomic` provides primitives that are meant to map directly to load-acquire and store-release instructions.

== Suitability for inclusion in the fast-track process

This extension is suitable for inclusion in the fast-track process because it is small, self-contained, and uncontroversial.
It adds only two new instructions (although with 8 variants of each of them).
It addresses a pressing need (being able to efficiently map the {cpp} memory model) that has already been considered (notes are already made in the memory model for its addition).
Mailing list discussion has been primarily over details, with the core aspects being uncontroversial.
This proposal is complete, even coming with SAIL code.
Therefore, this extension should be included in the fast-track process.
